import type { GeneratedApp } from "@/lib/generation-contract";

export type { GeneratedApp } from "@/lib/generation-contract";

type ShellOptions = { title: string; accent: string; body: string; script: string };

function shell({ title, accent, body, script }: ShellOptions) {
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:; connect-src 'none'; font-src 'none'; form-action 'none'; base-uri 'none'"/>
<title>${title}</title><style>
*{box-sizing:border-box}body{margin:0;background:#f7f8fb;color:#161923;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif;font-size:16px}button,input,select{font:inherit}button{cursor:pointer}.page{min-height:100vh;padding:34px}.app-head{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin:0 auto 24px;max-width:980px}.kicker{margin:0 0 7px;color:${accent};font-size:11px;font-weight:800;letter-spacing:.13em}.app-head h1{margin:0;font-size:30px;letter-spacing:-.035em}.app-head p{margin:8px 0 0;color:#6c7281;font-size:14px}.avatar{width:42px;height:42px;display:grid;place-items:center;border-radius:14px;background:${accent};color:white;font-weight:800;box-shadow:0 8px 24px ${accent}35}.surface{max-width:980px;margin:auto;border:1px solid #e3e5eb;border-radius:20px;background:white;box-shadow:0 18px 50px rgba(31,38,61,.07)}.btn{border:0;border-radius:10px;background:${accent};color:white;font-weight:700;padding:11px 16px}.field{width:100%;height:43px;border:1px solid #dfe2e9;border-radius:10px;background:#fff;padding:0 13px;color:#202430;outline:none}.field:focus{border-color:${accent};box-shadow:0 0 0 3px ${accent}18}@media(max-width:640px){.page{padding:20px 14px}.app-head h1{font-size:25px}.surface{border-radius:15px}}
</style></head><body><main class="page"><header class="app-head"><div><p class="kicker">ORBIT GENERATED APP</p><h1>${title}</h1><p>一个由自然语言生成的交互式网页应用</p></div><div class="avatar">O</div></header>${body}</main><script>${script}</script></body></html>`;
}

function todoApp(): GeneratedApp {
  const title = "学习任务管理器";
  const body = `<section class="surface">
  <div class="summary"><div><span>今日进度</span><strong id="progress">0%</strong></div><div class="bar"><i id="bar"></i></div><p id="summaryText">从完成第一项任务开始</p></div>
  <div class="create-row"><input id="taskInput" class="field" placeholder="输入一个学习任务…"/><select id="priority" class="field select"><option>普通</option><option>重要</option><option>紧急</option></select><button id="addBtn" class="btn">添加任务</button></div>
  <div class="filter-row"><div id="filters"><button class="filter active" data-filter="all">全部</button><button class="filter" data-filter="open">进行中</button><button class="filter" data-filter="done">已完成</button></div><span id="count">0 项任务</span></div>
  <div id="taskList" class="task-list"></div></section>
  <style>.summary{padding:25px 26px 22px;border-bottom:1px solid #eceef2;background:linear-gradient(120deg,#faf9ff,#fff);border-radius:20px 20px 0 0}.summary>div:first-child{display:flex;justify-content:space-between;align-items:center}.summary span{font-size:13px;font-weight:700}.summary strong{font-size:25px;color:#6554e8}.summary p{margin:9px 0 0;font-size:12px;color:#858b98}.bar{height:7px;margin-top:13px;overflow:hidden;border-radius:99px;background:#eceaf9}.bar i{display:block;width:0;height:100%;border-radius:inherit;background:#6554e8;transition:.3s}.create-row{display:grid;grid-template-columns:1fr 105px auto;gap:9px;padding:22px 26px}.select{appearance:none}.filter-row{display:flex;align-items:center;justify-content:space-between;padding:0 26px 14px}.filter{padding:7px 10px;border:0;border-radius:8px;background:transparent;color:#777e8e;font-size:12px;font-weight:600}.filter.active{background:#efedff;color:#5e4cdb}.filter-row span{color:#9197a4;font-size:12px}.task-list{padding:0 26px 24px}.task{display:grid;grid-template-columns:30px 1fr auto;align-items:center;gap:9px;padding:13px 0;border-top:1px solid #eff0f3}.check{width:22px;height:22px;display:grid;place-items:center;border:1px solid #ced2dc;border-radius:7px;background:white;color:white}.task.done .check{border-color:#6554e8;background:#6554e8}.task.done .task-title{text-decoration:line-through;color:#9ba0ac}.task-title{font-size:14px;font-weight:650}.task-meta{margin-top:4px;color:#969ca9;font-size:11px}.priority{padding:4px 7px;border-radius:6px;background:#f2f1fb;color:#766bb2}.delete{border:0;background:transparent;color:#adb2bd;font-size:18px}.empty{padding:34px 0;text-align:center;color:#949aa8;font-size:13px}@media(max-width:600px){.create-row{grid-template-columns:1fr auto;padding:18px}.create-row .select{display:none}.summary,.filter-row,.task-list{padding-left:18px;padding-right:18px}}</style>`;
  const script = `let tasks=[{id:1,title:'复习产品设计笔记',priority:'重要',done:true},{id:2,title:'完成交互原型',priority:'紧急',done:false},{id:3,title:'整理本周学习总结',priority:'普通',done:false}],filter='all';const list=document.getElementById('taskList'),input=document.getElementById('taskInput');function render(){const visible=tasks.filter(t=>filter==='all'||(filter==='done'?t.done:!t.done));list.innerHTML=visible.length?visible.map(t=>'<div class="task '+(t.done?'done':'')+'"><button class="check" data-check="'+t.id+'">✓</button><div><div class="task-title">'+t.title+'</div><div class="task-meta"><span class="priority">'+t.priority+'</span></div></div><button class="delete" data-delete="'+t.id+'">×</button></div>').join(''):'<div class="empty">这个分类里还没有任务</div>';const done=tasks.filter(t=>t.done).length,p=tasks.length?Math.round(done/tasks.length*100):0;document.getElementById('progress').textContent=p+'%';document.getElementById('bar').style.width=p+'%';document.getElementById('count').textContent=tasks.length+' 项任务';document.getElementById('summaryText').textContent=done===tasks.length&&tasks.length?'今天的任务都完成了':'已完成 '+done+' 项，还有 '+(tasks.length-done)+' 项'}document.getElementById('addBtn').onclick=()=>{if(!input.value.trim())return;tasks.unshift({id:Date.now(),title:input.value.trim(),priority:document.getElementById('priority').value,done:false});input.value='';render()};input.addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('addBtn').click()});list.onclick=e=>{const c=e.target.dataset.check,d=e.target.dataset.delete;if(c)tasks=tasks.map(t=>t.id==c?{...t,done:!t.done}:t);if(d)tasks=tasks.filter(t=>t.id!=d);render()};document.getElementById('filters').onclick=e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===e.target));render()};render();`;
  return { title, summary: "已生成任务管理、优先级、筛选和进度统计", html: shell({ title, accent: "#6554e8", body, script }) };
}

function calculatorApp(): GeneratedApp {
  const title = "贷款计算器";
  const body = `<section class="calc-grid"><div class="surface form-card"><h2>贷款信息</h2><label>贷款金额（元）</label><input id="amount" class="field" type="number" value="500000"/><label>年利率（%）</label><input id="rate" class="field" type="number" step="0.1" value="3.5"/><label>贷款期限（年）</label><input id="years" class="field" type="number" value="20"/><button id="calculate" class="btn">重新计算</button></div><div class="result-card"><span>预计每月还款</span><strong id="monthly">¥ 0</strong><p>等额本息估算结果</p><div class="breakdown"><div><small>还款总额</small><b id="total">¥ 0</b></div><div><small>利息总额</small><b id="interest">¥ 0</b></div><div><small>还款期数</small><b id="months">0 期</b></div></div><div class="tip">计算结果仅供参考，实际金额以金融机构为准。</div></div></section><style>.calc-grid{max-width:980px;margin:auto;display:grid;grid-template-columns:.8fr 1.2fr;gap:18px}.form-card{padding:26px}.form-card h2{margin:0 0 22px;font-size:18px}.form-card label{display:block;margin:16px 0 7px;color:#6c7281;font-size:12px;font-weight:650}.form-card .btn{width:100%;margin-top:22px}.result-card{padding:32px;border-radius:20px;background:linear-gradient(145deg,#171a29,#25233b);color:white;box-shadow:0 20px 48px rgba(29,25,60,.2)}.result-card>span{color:#aaa9bd;font-size:13px}.result-card>strong{display:block;margin-top:12px;font-size:42px;letter-spacing:-.04em}.result-card>p{margin:7px 0 31px;color:#85859b;font-size:12px}.breakdown{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.breakdown div{padding:15px;border:1px solid #38374c;border-radius:12px;background:#ffffff06}.breakdown small,.breakdown b{display:block}.breakdown small{color:#8e8da1;font-size:11px}.breakdown b{margin-top:8px;font-size:14px}.tip{margin-top:26px;padding-top:18px;border-top:1px solid #39384d;color:#77778d;font-size:11px}@media(max-width:680px){.calc-grid{grid-template-columns:1fr}.result-card>strong{font-size:34px}.breakdown{grid-template-columns:1fr}}</style>`;
  const script = `const money=n=>'¥ '+Math.round(n).toLocaleString('zh-CN');function calculate(){const amount=+document.getElementById('amount').value,rate=+document.getElementById('rate').value/100/12,months=+document.getElementById('years').value*12;const payment=rate?amount*rate*Math.pow(1+rate,months)/(Math.pow(1+rate,months)-1):amount/months;document.getElementById('monthly').textContent=money(payment);document.getElementById('total').textContent=money(payment*months);document.getElementById('interest').textContent=money(payment*months-amount);document.getElementById('months').textContent=months+' 期'}document.getElementById('calculate').onclick=calculate;calculate();`;
  return { title, summary: "已生成可实时计算月供与利息的贷款计算器", html: shell({ title, accent: "#4f46d8", body, script }) };
}

function dashboardApp(): GeneratedApp {
  const title = "客户数据看板";
  const body = `<section class="metrics"><div><span>客户总数</span><strong>128</strong><small>本月 +12</small></div><div><span>活跃客户</span><strong>84</strong><small>活跃率 65.6%</small></div><div><span>待跟进</span><strong>17</strong><small>其中 5 个高意向</small></div></section><section class="surface data-card"><div class="data-head"><div><h2>客户列表</h2><p>按姓名或公司快速查找</p></div><input id="search" class="field" placeholder="搜索客户…"/></div><div class="filters" id="filters"><button class="active" data-state="全部">全部</button><button data-state="活跃">活跃</button><button data-state="待跟进">待跟进</button></div><div class="table-wrap"><table><thead><tr><th>客户</th><th>公司</th><th>状态</th><th>最近联系</th></tr></thead><tbody id="rows"></tbody></table></div></section><style>.metrics{max-width:980px;margin:0 auto 18px;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.metrics div{padding:19px;border:1px solid #e4e6ec;border-radius:15px;background:white}.metrics span,.metrics small,.metrics strong{display:block}.metrics span{color:#737989;font-size:12px}.metrics strong{margin:8px 0 5px;font-size:27px}.metrics small{color:#6b5de8;font-size:11px}.data-card{padding:0;overflow:hidden}.data-head{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:22px 24px}.data-head h2{margin:0;font-size:17px}.data-head p{margin:4px 0 0;color:#8b91a0;font-size:11px}.data-head .field{max-width:230px}.filters{display:flex;gap:7px;padding:0 24px 16px}.filters button{padding:7px 11px;border:0;border-radius:8px;background:#f1f2f6;color:#7c8291;font-size:11px;font-weight:650}.filters button.active{background:#ece9ff;color:#5949d3}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:14px 24px;border-top:1px solid #eceef2;text-align:left;font-size:12px}th{background:#fafbfc;color:#858b99;font-size:10px;letter-spacing:.05em}td{color:#414756}.name{font-weight:700;color:#242936}.status{display:inline-block;padding:5px 8px;border-radius:99px;background:#ebf8f2;color:#26865d;font-size:10px}.status.follow{background:#fff3e6;color:#bc6a19}.empty{text-align:center;color:#969ba8}@media(max-width:650px){.metrics{grid-template-columns:1fr}.data-head{align-items:flex-start;flex-direction:column}.data-head .field{max-width:none}th,td{padding:12px 16px}th:nth-child(4),td:nth-child(4){display:none}}</style>`;
  const script = `const customers=[['林夏','北辰科技','活跃','今天'],['陈屿','远山设计','待跟进','2 天前'],['苏青','青禾教育','活跃','3 天前'],['周野','光年互动','待跟进','5 天前'],['顾言','墨白工作室','活跃','1 周前']];let state='全部';const search=document.getElementById('search'),rows=document.getElementById('rows');function render(){const q=search.value.toLowerCase(),data=customers.filter(x=>(state==='全部'||x[2]===state)&&(x[0]+x[1]).toLowerCase().includes(q));rows.innerHTML=data.length?data.map(x=>'<tr><td class="name">'+x[0]+'</td><td>'+x[1]+'</td><td><span class="status '+(x[2]==='待跟进'?'follow':'')+'">'+x[2]+'</span></td><td>'+x[3]+'</td></tr>').join(''):'<tr><td colspan="4" class="empty">没有找到符合条件的客户</td></tr>'}search.oninput=render;document.getElementById('filters').onclick=e=>{if(!e.target.dataset.state)return;state=e.target.dataset.state;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x===e.target));render()};render();`;
  return { title, summary: "已生成带搜索、状态筛选和指标卡片的客户看板", html: shell({ title, accent: "#6554e8", body, script }) };
}

function boardApp(): GeneratedApp {
  const title = "产品灵感看板";
  const body = `<section class="surface board"><div class="board-head"><div><h2>灵感收集箱</h2><p>记录想法，把灵感变成下一步行动</p></div><button id="newIdea" class="btn">添加想法</button></div><div id="ideas" class="ideas"></div></section><style>.board{padding:25px}.board-head{display:flex;align-items:center;justify-content:space-between;gap:20px}.board-head h2{margin:0;font-size:19px}.board-head p{margin:6px 0 0;color:#888e9d;font-size:12px}.ideas{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:24px}.idea{min-height:135px;padding:17px;border:1px solid #e6e7ec;border-radius:14px;background:#fafbfc}.idea span{display:inline-block;padding:4px 7px;border-radius:6px;background:#eeeaff;color:#6554d9;font-size:10px}.idea h3{margin:15px 0 7px;font-size:14px}.idea p{margin:0;color:#838998;font-size:11px;line-height:1.6}@media(max-width:650px){.ideas{grid-template-columns:1fr}}</style>`;
  const script = `let n=3;const ideas=document.getElementById('ideas');function add(title,desc){ideas.insertAdjacentHTML('afterbegin','<article class="idea"><span>想法 '+n+'</span><h3>'+title+'</h3><p>'+desc+'</p></article>');n++}add('更快的项目复盘','自动汇总关键结论和下一步行动。');add('团队灵感周报','把零散想法整理成可分享的每周简报。');document.getElementById('newIdea').onclick=()=>add('一个新的产品想法','刚刚创建，可以继续完善这条灵感。');`;
  return { title, summary: "已生成支持添加内容的产品灵感看板", html: shell({ title, accent: "#6554e8", body, script }) };
}

export function generateDemoApp(prompt: string): GeneratedApp {
  const normalized = prompt.toLowerCase();
  if (/贷款|房贷|月供|利率|计算器/.test(normalized)) return calculatorApp();
  if (/客户|crm|数据|看板|销售/.test(normalized)) return dashboardApp();
  if (/任务|待办|todo|学习|清单/.test(normalized)) return todoApp();
  return boardApp();
}
